export function createSideBarZH() {
  return {
    "/notes/": [
			{
				text: "Python基础",
				collapsed: false,
				items: [
					{ text: "01python数据模型", link: "/notes/Python基础/01python数据模型" },
					{ text: "02序列构成的数组", link: "/notes/Python基础/02序列构成的数组" },
					{ text: "03字典与集合", link: "/notes/Python基础/03字典与集合" },
					{ text: "04文本与字节序列", link: "/notes/Python基础/04文本与字节序列" },
					{ text: "05一等函数", link: "/notes/Python基础/05一等函数" },
					{ text: "06使用一等函数实现设计模式", link: "/notes/Python基础/06使用一等函数实现设计模式" },
					{ text: "07函数装饰器与闭包", link: "/notes/Python基础/07函数装饰器与闭包" },
					{ text: "08对象引用、可变性和垃圾回收", link: "/notes/Python基础/08对象引用、可变性和垃圾回收" },
					{ text: "09符合python风格的对象", link: "/notes/Python基础/09符合python风格的对象" },
					{ text: "10序列的修改、散列和切片", link: "/notes/Python基础/10序列的修改、散列和切片" },
					{ text: "11接口：从协议到抽象基类", link: "/notes/Python基础/11接口：从协议到抽象基类" },
					{ text: "12继承的优缺点", link: "/notes/Python基础/12继承的优缺点" },
					{ text: "13正确重载运算符", link: "/notes/Python基础/13正确重载运算符" },
					{ text: "14可迭代的对象、迭代器和生成器", link: "/notes/Python基础/14可迭代的对象、迭代器和生成器" },
					{ text: "15上下文管理和else块", link: "/notes/Python基础/15上下文管理和else块" },
					{ text: "16协程", link: "/notes/Python基础/16协程" },
					{ text: "17使用future处理并发", link: "/notes/Python基础/17使用future处理并发" },
					{ text: "18使用asyncio包处理并发", link: "/notes/Python基础/18使用asyncio包处理并发" },
					{ text: "19元编程", link: "/notes/Python基础/19元编程" },
				],
			},
			{
				text: "threejs入门",
				collapsed: false,
				items: [
					{ text: "01起步", link: "/notes/threejs入门/01起步" },
					{ text: "02一个基本的threejs应用", link: "/notes/threejs入门/02一个基本的threejs应用" },
					{ text: "03基于物理的渲染和照明", link: "/notes/threejs入门/03基于物理的渲染和照明" },
					{ text: "04变换、坐标系和场景图", link: "/notes/threejs入门/04变换、坐标系和场景图" },
					{ text: "05动画循环", link: "/notes/threejs入门/05动画循环" },
					{ text: "06纹理映射", link: "/notes/threejs入门/06纹理映射" },
					{ text: "07插件", link: "/notes/threejs入门/07插件" },
					{ text: "08环境光", link: "/notes/threejs入门/08环境光" },
					{ text: "09组织你的场景", link: "/notes/threejs入门/09组织你的场景" },
					{ text: "10内置几何体", link: "/notes/threejs入门/10内置几何体" },
					{ text: "11以gLTF格式加载3D模型", link: "/notes/threejs入门/11以gLTF格式加载3D模型" },
					{ text: "12threejs动画系统", link: "/notes/threejs入门/12threejs动画系统" },
				],
			},
			{
				text: "Rust基础学习",
				collapsed: false,
				items: [
					{ text: "01认识Cargo", link: "/notes/Rust基础学习/01认识Cargo" },
					{ text: "02变量绑定与解构", link: "/notes/Rust基础学习/02变量绑定与解构" },
					{ text: "03基本类型", link: "/notes/Rust基础学习/03基本类型" },
					{ text: "04所有权与借用", link: "/notes/Rust基础学习/04所有权与借用" },
					{ text: "05复合类型", link: "/notes/Rust基础学习/05复合类型" },
					{ text: "06流程控制", link: "/notes/Rust基础学习/06流程控制" },
					{ text: "07模式匹配", link: "/notes/Rust基础学习/07模式匹配" },
					{ text: "08方法Method", link: "/notes/Rust基础学习/08方法Method" },
					{ text: "09泛型", link: "/notes/Rust基础学习/09泛型" },
					{ text: "10特征", link: "/notes/Rust基础学习/10特征" },
					{ text: "11特征对象", link: "/notes/Rust基础学习/11特征对象" },
					{ text: "12深入特征", link: "/notes/Rust基础学习/12深入特征" },
					{ text: "13动态数组Vector", link: "/notes/Rust基础学习/13动态数组Vector" },
					{ text: "14KV存储HashMap", link: "/notes/Rust基础学习/14KV存储HashMap" },
					{ text: "15认识生命周期", link: "/notes/Rust基础学习/15认识生命周期" },
					{ text: "16返回值和错误处理", link: "/notes/Rust基础学习/16返回值和错误处理" },
					{ text: "17包和模块", link: "/notes/Rust基础学习/17包和模块" },
					{ text: "18注释和文档", link: "/notes/Rust基础学习/18注释和文档" },
					{ text: "19格式化输出", link: "/notes/Rust基础学习/19格式化输出" },
					{ text: "20实战-文件搜索工具", link: "/notes/Rust基础学习/20实战-文件搜索工具" },
				],
			},
			{
				text: "微前端设计与实现笔记",
				collapsed: false,
				items: [
					{ text: "01前端概览", link: "/notes/微前端设计与实现/01前端概览" },
					{ text: "02微前端原则", link: "/notes/微前端设计与实现/02微前端原则" },
					{ text: "03微前端的架构和挑战", link: "/notes/微前端设计与实现/03微前端的架构和挑战" },
					{ text: "04探索微前端架构", link: "/notes/微前端设计与实现/04探索微前端架构" },
					{ text: "05其他", link: "/notes/微前端设计与实现/05其他" },
				],
			},
			{
				text: "ChatGPT提示学习笔记",
				collapsed: false,
				items: [
					{ text: "1_2引言—指示", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记1_2" },
					{ text: "3迭代", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记3" },
					{ text: "4摘要", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记4" },
					{ text: "5推理", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记5" },
					{ text: "6转换", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记6" },
					{ text: "7扩展", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记7" },
					{ text: "8聊天机器人", link: "/notes/ChatGPT提示学习/ChatGPT提示学习笔记8" },
				],
			},
			{
				text: "算法与数据结构",
				collapsed: false,
				items: [
					{ text: "基础概念", link: "/notes/算法与数据结构/01基础概念" },
					{ text: "线性表", link: "/notes/算法与数据结构/02线性表" },
					{ text: "栈和队列", link: "/notes/算法与数据结构/03栈和队列" },
					{ text: "数组", link: "/notes/算法与数据结构/04数组" },
					{ text: "树", link: "/notes/算法与数据结构/05树" },
					{ text: "图", link: "/notes/算法与数据结构/06图" },
					{ text: "查找", link: "/notes/算法与数据结构/07查找" },
					{ text: "排序", link: "/notes/算法与数据结构/08排序" },
					{ text: "算法概述", link: "/notes/算法与数据结构/10算法概述" },
					{ text: "递归与分治", link: "/notes/算法与数据结构/11递归与分治" },
					{ text: "动态规划", link: "/notes/算法与数据结构/12动态规划" },
					{ text: "贪心算法", link: "/notes/算法与数据结构/13贪心算法" },
					{ text: "回溯与分支极限", link: "/notes/算法与数据结构/14回溯与分支界限" },
					{ text: "经典算法实现", link: "/notes/算法与数据结构/15经典算法实现" },
					{ text: "剑指Offer", link: "/notes/算法与数据结构/16剑指Offer" },
				],
			},
			{
				text: "计算机基础知识",
				collapsed: false,
				items: [{ text: "操作系统基础", link: "/notes/计算机基础知识/01操作系统基础" }],
			},
			{
				text: "数据库一期",
				collapsed: false,
				items: [
					{ text: "数据库系统概述", link: "/notes/数据库01/01数据库系统概述" },
					{ text: "关系数据库", link: "/notes/数据库01/02关系数据库" },
					{ text: "SQL(重点)", link: "/notes/数据库01/03SQL(重点)" },
					{ text: "数据库管理与维护(重点)", link: "/notes/数据库01/05数据库管理与维护(重点)" },
					{ text: "关系数据理论(重点)", link: "/notes/数据库01/06关系数据理论(重点)" },
					{ text: "数据库设计", link: "/notes/数据库01/07数据库设计" },
				],
			},
			{
				text: "JavaScript[待更新]",
				collapsed: false,
				items: [{ text: "JS常见手写面试题", link: "/notes/JavaScript/01JS常见手写面试题" }],
			},
			{
				text: "CSS相关[待更新]",
				collapsed: false,
				items: [],
			},
			{
				text: "Vue相关",
				collapsed: false,
				items: [
					{ text: "Vue3是如何运行的", link: "/notes/Vue相关/01Vue3是如何运行的" },
					{ text: "Vue3编译器", link: "/notes/Vue相关/02Vue3编译器" },
					{ text: "虚拟DOM", link: "/notes/Vue相关/03虚拟DOM" },
					{ text: "Vue3-Reactivity", link: "/notes/Vue相关/04Vue3-Reactivity" },
					{ text: "Mini-Vue", link: "/notes/Vue相关/05Mini-Vue" },
					{ text: "Vue3其他", link: "/notes/Vue相关/06Vue3其他" },
				],
			},
			{
				text: "NestJS",
				collapsed: false,
				items: [
					{ text: "controller", link: "/notes/NestJS/01controller" },
					{ text: "service", link: "/notes/NestJS/02service" },
					{ text: "module", link: "/notes/NestJS/03module" },
					{ text: "DTO", link: "/notes/NestJS/04DTO" },
					{ text: "postgreSQL", link: "/notes/NestJS/05postgreSQL" },
					{ text: "原理细节", link: "/notes/NestJS/06原理细节" },
					{ text: "应用配置", link: "/notes/NestJS/07应用配置" },
					{ text: "更多模块", link: "/notes/NestJS/08更多模块" },
					{ text: "openAPI", link: "/notes/NestJS/09openAPI" },
					{ text: "测试", link: "/notes/NestJS/10测试" },
				],
			},
			{
				text: "前端八股文",
				collapsed: false,
				items: [
					{ text: "HTML", link: "/notes/前端八股文/01HTML" },
					{ text: "CSS", link: "/notes/前端八股文/02CSS" },
					{ text: "JavaScript", link: "/notes/前端八股文/03JavaScript" },
					{ text: "Vue", link: "/notes/前端八股文/04Vue" },
					{ text: "计算机网络", link: "/notes/前端八股文/05计算机网络" },
					{ text: "浏览器原理", link: "/notes/前端八股文/06浏览器原理" },
					{ text: "性能优化", link: "/notes/前端八股文/07性能优化" },
				],
			},
			{
				text: "后端储备",
				collapsed: false,
				items: [
					{ text: "Django进阶学习笔记", link: "/notes/后端储备/01Django进阶学习笔记" },
					{ text: "DRF学习笔记", link: "/notes/后端储备/02DRF学习笔记" },
					{ text: "Redis学习笔记", link: "/notes/后端储备/03Redis学习笔记" },
				],
			},
			{
				text: "Web3.0",
				collapsed: false,
				items: [
					{ text: "Solidity8新特性", link: "/notes/Web3.0/00Solidity8新特性" },
					{ text: "Solidity8基本语法", link: "/notes/Web3.0/01Solidity8基本语法" },
					{ text: "Solidity8高级", link: "/notes/Web3.0/02Solidity8高级" },
					{ text: "Solidity8进阶", link: "/notes/Web3.0/03Solidity8进阶" },
				],
			},
			{
				text: "AI相关[待更新]",
				collapsed: false,
				items: [],
			},
		].map((item, i) => (!i ? item : { ...item, collapsed: true })),
  }
}

export function createSideBarEN() {
  return {
    "/en/notes/": [
			{
				text: "Python基础",
				collapsed: false,
				items: [
					{ text: "01python数据模型", link: "/en/notes/Python基础/01python数据模型" },
					{ text: "02序列构成的数组", link: "/en/notes/Python基础/02序列构成的数组" },
					{ text: "03字典与集合", link: "/en/notes/Python基础/03字典与集合" },
					{ text: "04文本与字节序列", link: "/en/notes/Python基础/04文本与字节序列" },
					{ text: "05一等函数", link: "/en/notes/Python基础/05一等函数" },
					{ text: "06使用一等函数实现设计模式", link: "/en/notes/Python基础/06使用一等函数实现设计模式" },
					{ text: "07函数装饰器与闭包", link: "/en/notes/Python基础/07函数装饰器与闭包" },
					{ text: "08对象引用、可变性和垃圾回收", link: "/en/notes/Python基础/08对象引用、可变性和垃圾回收" },
					{ text: "09符合python风格的对象", link: "/en/notes/Python基础/09符合python风格的对象" },
					{ text: "10序列的修改、散列和切片", link: "/en/notes/Python基础/10序列的修改、散列和切片" },
					{ text: "11接口：从协议到抽象基类", link: "/en/notes/Python基础/11接口：从协议到抽象基类" },
					{ text: "12继承的优缺点", link: "/en/notes/Python基础/12继承的优缺点" },
					{ text: "13正确重载运算符", link: "/en/notes/Python基础/13正确重载运算符" },
					{ text: "14可迭代的对象、迭代器和生成器", link: "/en/notes/Python基础/14可迭代的对象、迭代器和生成器" },
					{ text: "15上下文管理和else块", link: "/en/notes/Python基础/15上下文管理和else块" },
					{ text: "16协程", link: "/en/notes/Python基础/16协程" },
					{ text: "17使用future处理并发", link: "/en/notes/Python基础/17使用future处理并发" },
					{ text: "18使用asyncio包处理并发", link: "/en/notes/Python基础/18使用asyncio包处理并发" },
					{ text: "19元编程", link: "/en/notes/Python基础/19元编程" },
				],
			},
			{
				text: "threejs入门",
				collapsed: false,
				items: [
					{ text: "01起步", link: "/en/notes/threejs入门/01起步" },
					{ text: "02一个基本的threejs应用", link: "/en/notes/threejs入门/02一个基本的threejs应用" },
					{ text: "03基于物理的渲染和照明", link: "/en/notes/threejs入门/03基于物理的渲染和照明" },
					{ text: "04变换、坐标系和场景图", link: "/en/notes/threejs入门/04变换、坐标系和场景图" },
					{ text: "05动画循环", link: "/en/notes/threejs入门/05动画循环" },
					{ text: "06纹理映射", link: "/en/notes/threejs入门/06纹理映射" },
					{ text: "07插件", link: "/en/notes/threejs入门/07插件" },
					{ text: "08环境光", link: "/en/notes/threejs入门/08环境光" },
					{ text: "09组织你的场景", link: "/en/notes/threejs入门/09组织你的场景" },
					{ text: "10内置几何体", link: "/en/notes/threejs入门/10内置几何体" },
					{ text: "11以gLTF格式加载3D模型", link: "/en/notes/threejs入门/11以gLTF格式加载3D模型" },
					{ text: "12threejs动画系统", link: "/en/notes/threejs入门/12threejs动画系统" },
				],
			},
			{
				text: "Rust基础学习",
				collapsed: false,
				items: [
					{ text: "01认识Cargo", link: "/en/notes/Rust基础学习/01认识Cargo" },
					{ text: "02变量绑定与解构", link: "/en/notes/Rust基础学习/02变量绑定与解构" },
					{ text: "03基本类型", link: "/en/notes/Rust基础学习/03基本类型" },
					{ text: "04所有权与借用", link: "/en/notes/Rust基础学习/04所有权与借用" },
					{ text: "05复合类型", link: "/en/notes/Rust基础学习/05复合类型" },
					{ text: "06流程控制", link: "/en/notes/Rust基础学习/06流程控制" },
					{ text: "07模式匹配", link: "/en/notes/Rust基础学习/07模式匹配" },
					{ text: "08方法Method", link: "/en/notes/Rust基础学习/08方法Method" },
					{ text: "09泛型", link: "/en/notes/Rust基础学习/09泛型" },
					{ text: "10特征", link: "/en/notes/Rust基础学习/10特征" },
					{ text: "11特征对象", link: "/en/notes/Rust基础学习/11特征对象" },
					{ text: "12深入特征", link: "/en/notes/Rust基础学习/12深入特征" },
					{ text: "13动态数组Vector", link: "/en/notes/Rust基础学习/13动态数组Vector" },
					{ text: "14KV存储HashMap", link: "/en/notes/Rust基础学习/14KV存储HashMap" },
					{ text: "15认识生命周期", link: "/en/notes/Rust基础学习/15认识生命周期" },
					{ text: "16返回值和错误处理", link: "/en/notes/Rust基础学习/16返回值和错误处理" },
					{ text: "17包和模块", link: "/en/notes/Rust基础学习/17包和模块" },
					{ text: "18注释和文档", link: "/en/notes/Rust基础学习/18注释和文档" },
					{ text: "19格式化输出", link: "/en/notes/Rust基础学习/19格式化输出" },
					{ text: "20实战-文件搜索工具", link: "/en/notes/Rust基础学习/20实战-文件搜索工具" },
				],
			},
			{
				text: "微前端设计与实现笔记",
				collapsed: false,
				items: [
					{ text: "01前端概览", link: "/en/notes/微前端设计与实现/01前端概览" },
					{ text: "02微前端原则", link: "/en/notes/微前端设计与实现/02微前端原则" },
					{ text: "03微前端的架构和挑战", link: "/en/notes/微前端设计与实现/03微前端的架构和挑战" },
					{ text: "04探索微前端架构", link: "/en/notes/微前端设计与实现/04探索微前端架构" },
					{ text: "05其他", link: "/en/notes/微前端设计与实现/05其他" },
				],
			},
			{
				text: "ChatGPT提示学习笔记",
				collapsed: false,
				items: [
					{ text: "1_2引言—指示", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记1_2" },
					{ text: "3迭代", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记3" },
					{ text: "4摘要", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记4" },
					{ text: "5推理", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记5" },
					{ text: "6转换", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记6" },
					{ text: "7扩展", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记7" },
					{ text: "8聊天机器人", link: "/en/notes/ChatGPT提示学习/ChatGPT提示学习笔记8" },
				],
			},
			{
				text: "算法与数据结构",
				collapsed: false,
				items: [
					{ text: "基础概念", link: "/en/notes/算法与数据结构/01基础概念" },
					{ text: "线性表", link: "/en/notes/算法与数据结构/02线性表" },
					{ text: "栈和队列", link: "/en/notes/算法与数据结构/03栈和队列" },
					{ text: "数组", link: "/en/notes/算法与数据结构/04数组" },
					{ text: "树", link: "/en/notes/算法与数据结构/05树" },
					{ text: "图", link: "/en/notes/算法与数据结构/06图" },
					{ text: "查找", link: "/en/notes/算法与数据结构/07查找" },
					{ text: "排序", link: "/en/notes/算法与数据结构/08排序" },
					{ text: "算法概述", link: "/en/notes/算法与数据结构/10算法概述" },
					{ text: "递归与分治", link: "/en/notes/算法与数据结构/11递归与分治" },
					{ text: "动态规划", link: "/en/notes/算法与数据结构/12动态规划" },
					{ text: "贪心算法", link: "/en/notes/算法与数据结构/13贪心算法" },
					{ text: "回溯与分支极限", link: "/en/notes/算法与数据结构/14回溯与分支界限" },
					{ text: "经典算法实现", link: "/en/notes/算法与数据结构/15经典算法实现" },
					{ text: "剑指Offer", link: "/en/notes/算法与数据结构/16剑指Offer" },
				],
			},
			{
				text: "计算机基础知识",
				collapsed: false,
				items: [{ text: "操作系统基础", link: "/en/notes/计算机基础知识/01操作系统基础" }],
			},
			{
				text: "数据库一期",
				collapsed: false,
				items: [
					{ text: "数据库系统概述", link: "/en/notes/数据库01/01数据库系统概述" },
					{ text: "关系数据库", link: "/en/notes/数据库01/02关系数据库" },
					{ text: "SQL(重点)", link: "/en/notes/数据库01/03SQL(重点)" },
					{ text: "数据库管理与维护(重点)", link: "/en/notes/数据库01/05数据库管理与维护(重点)" },
					{ text: "关系数据理论(重点)", link: "/en/notes/数据库01/06关系数据理论(重点)" },
					{ text: "数据库设计", link: "/en/notes/数据库01/07数据库设计" },
				],
			},
			{
				text: "JavaScript[待更新]",
				collapsed: false,
				items: [{ text: "JS常见手写面试题", link: "/en/notes/JavaScript/01JS常见手写面试题" }],
			},
			{
				text: "CSS相关[待更新]",
				collapsed: false,
				items: [],
			},
			{
				text: "Vue相关",
				collapsed: false,
				items: [
					{ text: "Vue3是如何运行的", link: "/en/notes/Vue相关/01Vue3是如何运行的" },
					{ text: "Vue3编译器", link: "/en/notes/Vue相关/02Vue3编译器" },
					{ text: "虚拟DOM", link: "/en/notes/Vue相关/03虚拟DOM" },
					{ text: "Vue3-Reactivity", link: "/en/notes/Vue相关/04Vue3-Reactivity" },
					{ text: "Mini-Vue", link: "/en/notes/Vue相关/05Mini-Vue" },
					{ text: "Vue3其他", link: "/en/notes/Vue相关/06Vue3其他" },
				],
			},
			{
				text: "NestJS",
				collapsed: false,
				items: [
					{ text: "controller", link: "/en/notes/NestJS/01controller" },
					{ text: "service", link: "/en/notes/NestJS/02service" },
					{ text: "module", link: "/en/notes/NestJS/03module" },
					{ text: "DTO", link: "/en/notes/NestJS/04DTO" },
					{ text: "postgreSQL", link: "/en/notes/NestJS/05postgreSQL" },
					{ text: "原理细节", link: "/en/notes/NestJS/06原理细节" },
					{ text: "应用配置", link: "/en/notes/NestJS/07应用配置" },
					{ text: "更多模块", link: "/en/notes/NestJS/08更多模块" },
					{ text: "openAPI", link: "/en/notes/NestJS/09openAPI" },
					{ text: "测试", link: "/en/notes/NestJS/10测试" },
				],
			},
			{
				text: "前端八股文",
				collapsed: false,
				items: [
					{ text: "HTML", link: "/en/notes/前端八股文/01HTML" },
					{ text: "CSS", link: "/en/notes/前端八股文/02CSS" },
					{ text: "JavaScript", link: "/en/notes/前端八股文/03JavaScript" },
					{ text: "Vue", link: "/en/notes/前端八股文/04Vue" },
					{ text: "计算机网络", link: "/en/notes/前端八股文/05计算机网络" },
					{ text: "浏览器原理", link: "/en/notes/前端八股文/06浏览器原理" },
					{ text: "性能优化", link: "/en/notes/前端八股文/07性能优化" },
				],
			},
			{
				text: "后端储备",
				collapsed: false,
				items: [
					{ text: "Django进阶学习笔记", link: "/en/notes/后端储备/01Django进阶学习笔记" },
					{ text: "DRF学习笔记", link: "/en/notes/后端储备/02DRF学习笔记" },
					{ text: "Redis学习笔记", link: "/en/notes/后端储备/03Redis学习笔记" },
				],
			},
			{
				text: "Web3.0",
				collapsed: false,
				items: [
					{ text: "Solidity8新特性", link: "/en/notes/Web3.0/00Solidity8新特性" },
					{ text: "Solidity8基本语法", link: "/en/notes/Web3.0/01Solidity8基本语法" },
					{ text: "Solidity8高级", link: "/en/notes/Web3.0/02Solidity8高级" },
					{ text: "Solidity8进阶", link: "/en/notes/Web3.0/03Solidity8进阶" },
				],
			},
			{
				text: "AI相关[待更新]",
				collapsed: false,
				items: [],
			},
		].map((item, i) => (!i ? item : { ...item, collapsed: true })),
  }
}
